version: '3'

services:
    mysql:
        image: mysql:latest
        container_name: mysql-container
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: Prueba123*
        ports:
            - "3306:3306"
        volumes:
            - mysql-data2:/var/lib/mysql
volumes:
    mysql-data2:
